---
openapi: 3.0.3
info:
  title: rest-heroes API
  version: 1.0.0-SNAPSHOT
tags:
  - name: heroes
paths:
  /api/heroes:
    get:
      tags:
        - heroes
      summary: Returns all the heroes from the database
      operationId: get-all-heroes
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Hero"
    put:
      tags:
        - heroes
      summary: Updates an exiting hero
      operationId: update-hero
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Hero"
      responses:
        "200":
          description: The updated hero
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hero"
    post:
      tags:
        - heroes
      summary: Creates a valid hero
      operationId: create-hero
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Hero"
      responses:
        "201":
          description: The URI of the created hero
          content:
            application/json:
              schema:
                format: uri
                type: string
  /api/heroes/hello:
    get:
      tags:
        - heroes
      operationId: hello
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /api/heroes/random:
    get:
      tags:
        - heroes
      summary: Returns a random hero
      operationId: get-random-hero
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hero"
  /api/heroes/{id}:
    get:
      tags:
        - heroes
      summary: Returns a hero for a given identifier
      operationId: get-hero
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hero"
        "204":
          description: The hero is not found for a given identifier
    delete:
      tags:
        - heroes
      summary: Deletes an exiting hero
      operationId: delete-hero
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "204":
          description: No Content
components:
  schemas:
    Hero:
      required:
        - name
        - level
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          maxLength: 50
          minLength: 3
          type: string
        otherName:
          type: string
        level:
          format: int32
          minimum: 1
          type: integer
        picture:
          type: string
        powers:
          type: string
